name: abe
description: "A.B.E. - American Backlog Enhancement, a project tracking and management application."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  webview_flutter: ^4.4.0

  cupertino_icons: ^1.0.0

flutter:
  # no assets yet
