name: game
description: "Game scaffold package depending on core."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../common/core
  markdown_view:
    path: ../../common/markdown_view

  cupertino_icons: ^1.0.0

flutter:
  # no assets yet
