name: web_2
description: "Web 2.0 scaffold package depending on core."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  markdown_view:
    path: ../markdown_view

  cupertino_icons: ^1.0.0

flutter:
  # no assets yet
