name: we_the_people
description: "We the People - a third party movement application."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  markdown_view:
    path: ../markdown_view

  cupertino_icons: ^1.0.0

flutter:
  # no assets yet
